### ISSUE TITLE
help

### ISSUE THREAD

**Issue by srmsh** [square/certigo#102]
![20161207085958](https://cloud.githubusercontent.com/assets/11769478/20951387/6b1712b6-bc60-11e6-8b25-a545919763cc.png)

it is not work

**Comment by srmsh** [comment]
@xaviershay

**Comment by mcpherrinm** [comment]
Hello @srmsh 

I'm happy to help with whatever problems you're having, but I'm afraid I don't have enough information from your picture alone.

What are you trying to do?  What did you expect to happen?  What actually happened?
Can you share the certificate files it failed on?

**Comment by mcpherrinm** [comment]
Closing due to lack of response.
