### ISSUE TITLE
Add warnings about pathlen constraint on CAs

### ISSUE THREAD

**Issue by mcpherrinm** [square/certigo#106]

**Comment by csstaub** [comment]
How do you know that pathlen:0 is the correct value for the given CA certificate? What about cross-signed roots? You wouldn't want to warn on a larger pathlen there, I think.

**Comment by mcpherrinm** [comment]
I think the direct signer of a leaf certificate should always have pathlen:0

**Comment by mbyczkowski** [comment]
Seems like it would be hard to provide useful warnings that would apply to general population of certigo users.
