### ISSUE TITLE
Feature request: An option for terser output from at least 'certigo connect'

### ISSUE THREAD

**Issue by siebenmann** [square/certigo#126]
`certigo connect` is awesome for providing detailed information about the TLS certificate and certificate chain actively being used by a service. But sometimes displaying all that information is overkill, and what I really want to know is basic information about the certificate, the certificate chain, and the validity of the whole chain. So, this is a feature request for some sort of 'terse' flag for at least `certigo connect` that would produce terser output. If this is a feature that would be accepted for certigo, I'd be happy to see if I can do at least a preliminary implementation.

What should be included in terse output is certainly an open question. What I think I would find most useful is:
* TLS version and cipher suite
* the DNS names covered between the certificate's CN and alternate DNS names
* the certificate's not before and not after dates
* the shortest valid certificate chain (possibly with not-after dates for each chained certificate)

A more feature-rich 'terse output' implementation might provide additional options to control some of these, but that might be best done in separate enhancements.

**Comment by csstaub** [comment]
+1, we should make the default output terser. It's also possible to do filtering based on the JSON output if you like, e.g. if you just want to select CN+DNS names:

```
certigo connect --json google.com:443 | jq '.certificates[0] | [.subject.common_name] + .dns_names'
```

**Comment by mcpherrinm** [comment]
I posted my half-done PR, it can be finished up pretty easily

**Comment by mcpherrinm** [comment]
I think cert output is sufficiently terse in non-verbose mode now.

We should still have better output for trust chains.  I'll open a second bug to track that work.
