### ISSUE TITLE
Enhancement: support SMTP STARTTLS with an EHLO name other than 'localhost'

### ISSUE THREAD

**Issue by siebenmann** [square/certigo#135]
The Go net/smtp package that certigo's starttls.GetConnectionState uses defaults to EHLO'ing with the name `localhost`. Unfortunately not all SMTP servers accept this EHLO name; since it's frequently abused by bad clients, it's also frequently rejected, which hampers using `certigo connect -t smtp ...` to obtain TLS certificate information from various SMTP servers.

The official way to supply a non-localhost name is to explicitly call `smtp.Hello()` immediately after connecting (before you do anything else). Probably the simplest approach here is to add an extra command line argument to specify the EHLO name to use, since this avoids the morass of trying to automatically determine a plausible host name for the connection.

**Comment by mcpherrinm** [comment]
Seems easy enough, just need to plumb out a command line flag.

https://github.com/square/certigo/pull/136

**Comment by mcpherrinm** [comment]
We also hardcode a username of 'certigo' in mysql and postgres, which we could allow changing too.

**Comment by mcpherrinm** [comment]
@siebenmann Can you take a look at the PR I've posted and see if it meets your needs? I don't know of any SMTP servers offhand that reject the `localhost` EHLO.

**Comment by siebenmann** [comment]
Belatedly: the PR (now landed) works for me and nicely meets my needs. The default is less likely to have problems and if it does, you've given me a way of fully specifying the EHLO name so I can set it to whatever is necessary to get a server to talk to me. Thanks!
