### ISSUE TITLE
go/src/github.com/square/certigo/lib/tls.go:164:2: undefined: tls.VersionTLS13

### ISSUE THREAD

**Issue by grinapo** [square/certigo#186]
```
$ go get -u github.com/square/certigo
# github.com/square/certigo/lib
/home/anybody/go/src/github.com/square/certigo/lib/tls.go:164:2: undefined: tls.VersionTLS13
```

**Comment by mbyczkowski** [comment]
@grinapo what's your Go version? `tls.VersionTLS13` was introduced in Go 1.12.

**Comment by grinapo** [comment]
Debian/sid have 1.11.6 by default, but I see 1.12.5 is installable. 

Indeed, installing 1.12 and forcing it gets certigo and it seem to work fine.
