### ISSUE TITLE
Add an option to verify on connect

### ISSUE THREAD

**Issue by thefotios** [square/certigo#188]
One thing I've been using `certigo` for is to validate that our systems have proper SSL certificates installed (since we're using an internal CA). The "problem" is that `certigo connect` will show whether there are issues with the certificate, but it exits with a `0` regardless. 

For instance:
```
$ certigo connect --name xxx github.com:443  
** TLS Connection **
.....
Failed to verify certificate chain:
        x509: certificate is valid for github.com, www.github.com, not xxx
$ echo $?
0
```
vs
```
$ certigo connect --pem github.com:443 | certigo verify --name xxx
Failed to verify certificate chain:
        x509: certificate is valid for github.com, www.github.com, not xxx
$ echo $?
1
```

It would be useful for `connect` to have an option like `--verify` that fails if the certificate is invalid.

**Comment by csstaub** [comment]
I think that's a good idea, we should add this.

In the meantime you can also use jq to do this:
```
certigo connect -j expired.badssl.com | jq -e '.verify_result.error == null'
```

In this example `-j` tells certigo to produce JSON output, and `-e` tells JQ to exit with 0/1 depending on the truthy-ness value of the expression. So you'll get 0 if `.verify_result.error` is null (no error), and 1 if it is present (there was an error).
