### ISSUE TITLE
Build failure with current Go versions due to needing a go.sum update for github.com/fatih/color

### ISSUE THREAD

**Issue by siebenmann** [square/certigo#229]
It's simplest to illustrate this:
```
$ git clone https://github.com/square/certigo
$ cd certigo
$ go version
go version go1.16.3 linux/amd64
$ go build
lib/display.go:32:2: missing go.sum entry for module providing package github.com/fatih/color (imported by github.com/square/certigo/lib); to add:
        go get github.com/square/certigo/lib
```
This issue is present with versions of Go all the way back to Go v1.13 (the oldest version I have on hand), although in older versions building without '-mod=readonly' will silently update go.sum for you.

**Comment by mbyczkowski** [comment]
I believe this has been fixed already. Feel free to re-open if you're still seeing issues.
