### ISSUE TITLE
Support `-h` in addition to `--help`

### ISSUE THREAD

**Issue by bbkane** [square/certigo#233]
```
$ certigo -h
unknown short flag '-h', try --help
```

As a lazy person, I prefer to use `-h`. `kingpin` has [builtin support](https://github.com/alecthomas/kingpin#supporting--h-for-help) for the short help flag. Would you accept a pull request if I added `app.HelpFlag.Short('h')` and tested the change by running `certigo -h`?

**Comment by mbyczkowski** [comment]
Absolutely! PRs welcome! :)
