### ISSUE TITLE
OCSP unauhtorized error

### ISSUE THREAD

**Issue by kjur** [square/certigo#272]
When I execute following command:
```
certigo connect www.google.com
```
It raise following OCSP error:
```
** CERTIFICATE 3 **
Valid: 2020-06-19 00:00 UTC to 2028-01-28 00:00 UTC
Subject:
	C=US, O=Google Trust Services LLC, CN=GTS Root R1
Issuer:
	C=BE, O=GlobalSign nv-sa, OU=Root CA, CN=GlobalSign Root CA
Certificate has OCSP extension, but was unable to check status:
	ocsp: error from server: unauthorized
```
How can I avoid this error? In other certificate validation tools, they don't raise such error including intermediate CA OCSP validation.

**Comment by jdtw** [comment]
Thanks for reporting this -- it looks like a longstanding bug in our OCSP handling. I'll work on a fix.
