### ISSUE TITLE
Expose list of supported formats

### ISSUE THREAD

**Issue by alokmenghrajani** [square/certigo#61]
It seems users currently have to guess (or look at the source code) to figure out the set of valid formats. 

We should improve the output of `certigo dump --help`. We could also list all the valid formats when an invalid one is provided (currently, we only return `unknown file type: xyz`).

**Comment by christodenny** [comment]
Is this different from https://github.com/square/certigo/issues/23?

**Comment by alokmenghrajani** [comment]
Yes, different issues. This issue is about telling users which file formats we support. 

https://github.com/square/certigo/issues/23 is about printing information about unknown x509 extensions.

**Comment by mcpherrinm** [comment]
The list is in the help text:

    -f, --format=FORMAT      Format of given input (PEM, DER, JCEKS, PKCS12; heuristic if missing).
