### ISSUE TITLE
OpenSSL doesn't support PEM headers

### ISSUE THREAD

**Issue by csstaub** [square/certigo#89]
We currently print PEM headers when the `--pem` flag is passed with extra information, e.g. the friendly name of an entry in a PKCS12 keystore. However, OpenSSL can't handle these and will refuse to parse them. We should consider scrubbing headers on PEM output.

**Comment by jeroenooms** [comment]
The openssl C api has very extensive PEM parsers. For example to parse from a memory buffer (BIO):

 `PEM_read_bio_RSAPublicKey`
 `PEM_read_bio_PUBKEY`
 `PEM_read_bio_X509`

**Comment by csstaub** [comment]
I think you're misunderstanding. OpenSSL will not accept a PEM block that has extra header fields. I'm aware that it can parse regular PEM blocks without headers. 

For example, OpenSSL does *not* accept a PEM block like this:
```
-----BEGIN CERTIFICATE-----
friendlyName: example-small-key

MIICKzCCAZQCCQDHlr/u+lfb8jANBgkqhkiG9w0BAQsFADBaMQswCQYDVQQGEwJV
UzELMAkGA1UECBMCQ0ExEDAOBgNVBAoTB2NlcnRpZ28xEDAOBgNVBAsTB2V4YW1w
bGUxGjAYBgNVBAMTEWV4YW1wbGUtc21hbGwta2V5MB4XDTE2MDYxMDIyMTQxMloX
DTIzMDQxNTIyMTQxMlowWjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRAwDgYD
VQQKEwdjZXJ0aWdvMRAwDgYDVQQLEwdleGFtcGxlMRowGAYDVQQDExFleGFtcGxl
LXNtYWxsLWtleTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAlzyCIeP1T87k
1rHVMtbaGXIWpK/VQuvuXwig+e3ct1ajA4bw0BAInXZ37FEGGSCUix0k/CjH2Nlt
GREtwbahE0k5oTkVbA5XS4xkNs0M0poAFN5OiFKEAqZ014hqhvKnEUQ2oTe9SVOR
Ww49mLNg36AIEE2Fu2KQb/VT90cwwD0CAwEAATANBgkqhkiG9w0BAQsFAAOBgQBV
sJ4Vb2L1ywLVeAxNqY0PZqS7a8Q2GLhNr5V+3hOoWn7bwqQ7L06UJGSrcLOPZeIH
IWM20aOFHSTWbocd4f+m6s3llyXwBBlK2BPZbWv0OeAHgjN9AVav4flAZ4oD2GxA
aJkGAXmR9QzZNJLai5mv3L/B/p/NxeU3UGfaySxVvw==
-----END CERTIFICATE-----
```

...but if you remove the `friendlyName` header, it will happily accept it.

You can try it yourself with `openssl x509` to see that it fails (I tested with 1.0.2h).
